name: Source4Droid Testing Build.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Change directory.
        run: cd $GITHUB_WORKSPACE/src
      - name: Install dependencies.
        run: sudo apt install gcc-multilib g++-multilib
      - name: Give permissions.
        run: chmod a+x buildandroid.sh && chmod a+x devtools/bin/vpc
      -name: Build.
        run: ./buildandroid.sh